// Generated by ContractTypesTest from the backend API records. Do not edit by hand.
// Fields of records that omit nulls (the WebSocket protocol) are optional here.

export interface AccessDto {
  access: AccessStatusDto;
  drainMode: boolean;
}

export interface AccessStatusDto {
  freeGamesEnabled: boolean;
  freeGameAvailable: boolean;
  nextFreeGameAt: string;
  passes: PassStatusDto[];
  upcomingPasses: PassStatusDto[];
  nextGame: string;
  paywallReason: ErrorCode;
}

export interface AdminMetricsDto {
  from: string;
  to: string;
  games: GameMetricsDto;
  money: MoneyMetricsDto;
  ai: AiMetricsDto;
  funnel: FunnelMetricsDto;
  live: LiveStatsDto;
  days: DayMetricsDto[];
}

export interface AdminUserDto {
  id: string;
  email: string;
  displayName: string;
  role: string;
  googleLinked: boolean;
  createdAt: string;
  lastLoginAt: string;
  games: number;
  passes: PassStatusDto[];
}

export interface AiCallDto {
  id: number;
  createdAt: string;
  purpose: string;
  provider: string;
  model: string;
  promptVersion: string;
  outcome: string;
  inputTokens: number;
  outputTokens: number;
  ttsChars: number;
  costMicros: number;
  latencyMs: number;
  freeGame: boolean;
  gameSessionId: string;
  roomCode: string;
  error: string;
}

export interface AiCallSummaryDto {
  at: string;
  purpose: string;
  model: string;
  outcome: string;
  latencyMs: number;
  error: string;
}

export interface AiMetricsDto {
  costMicros: number;
  freeGameCostMicros: number;
  costPerGameMicros: number;
  calls: number;
  failures: number;
  costByPurpose: Record<string, number>;
}

export interface AiStatusDto {
  keyConfigured: boolean;
  model: string;
  lastCall: AiCallSummaryDto;
  lastFailure: AiCallSummaryDto;
  rateLimits: RateLimitsDto;
}

export interface AnswerProgressDto {
  playerId?: string;
  answered: number;
  total: number;
}

export interface AssignmentDto {
  duelId?: string;
  prompt?: string;
  answer?: string;
}

export interface AudienceDto {
  voted: boolean;
  total?: number;
}

export interface AudienceTokenDto {
  audienceToken: string;
}

export interface AuthConfigDto {
  googleEnabled: boolean;
}

export interface CheckoutConfigDto {
  available: boolean;
  environment: string;
  clientToken: string;
  offers: OfferDto[];
  email: string;
  customData: Record<string, string>;
  supportEmail: string;
}

export interface ClientEventRequestDto {
  event: string;
  anonymousId: string;
  properties: Record<string, unknown>;
}

export interface CodeRequestDto {
  email: string;
  code: string;
}

export interface CodeSentDto {
  sent: boolean;
  resendAfterSeconds: number;
}

export interface CreateRoomRequestDto {
  tone: string;
  length: string;
  mode: string;
  hideCode: boolean;
  adultsConfirmed: boolean;
  language: string;
}

export interface CreatedRoomDto {
  code: string;
  screenToken: string;
  joinUrl: string;
}

export interface CsrfDto {
  headerName: string;
  token: string;
}

export interface CurrencyRevenueDto {
  currency: string;
  grossMinor: number;
  refundedMinor: number;
  netMinor: number;
}

export interface CurrencyTotalDto {
  currency: string;
  amountMinor: number;
}

export interface DayMetricsDto {
  date: string;
  games: number;
  paidGames: number;
  aiCostMicros: number;
}

export interface DrainRequestDto {
  enabled: boolean;
}

export interface DrainStateDto {
  drainMode: boolean;
  live: LiveStatsDto;
}

export interface EmailRequestDto {
  email: string;
  language: string;
}

export type ErrorCode = "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "VALIDATION_FAILED" | "RATE_LIMITED" | "INTERNAL" | "EMAIL_SEND_FAILED" | "CODE_INVALID" | "CODE_EXPIRED" | "CODE_LOCKED" | "LINK_INVALID" | "GOOGLE_DISABLED" | "ROOM_NOT_FOUND" | "ROOM_FULL" | "ROOM_LOCKED" | "ROOM_IN_PROGRESS" | "NAME_TAKEN" | "NAME_INVALID" | "NOT_STREAMER_MODE" | "AUDIENCE_FULL" | "SCREENS_FULL" | "DRAIN_MODE" | "PAYWALL_FREE_LIMIT" | "PAYWALL_MONTHLY_LIMIT" | "BUDGET_PAUSED" | "PAYMENTS_UNAVAILABLE" | "NOT_ALLOWED" | "INVALID_PHASE" | "NOT_ENOUGH_PLAYERS" | "MODERATION_BLOCKED" | "MODERATION_UNAVAILABLE" | "DOSSIER_LIMIT" | "BAD_MESSAGE";

export interface ErrorDetailDto {
  code: string;
  message: string;
  details: Record<string, unknown>;
}

export interface ErrorDto {
  error: ErrorDetailDto;
}

export interface FailedWebhookDto {
  provider: string;
  eventId: string;
  eventType: string;
  receivedAt: string;
  lastError: string;
}

export interface FeedbackRequestDto {
  rating: number;
  comment: string;
}

export interface FinaleDto {
  standings?: PlayerDto[];
  titles?: Record<string, string>;
  winnerIds?: string[];
  answerOfNight?: string;
  answerOfNightPrompt?: string;
  answerOfNightAuthorId?: string;
  speech?: string;
  ready: boolean;
}

export interface FunnelMetricsDto {
  newHosts: number;
  activeHosts: number;
  payingHosts: number;
  conversion: number;
}

export type GameLength = "SHORT" | "LONG";

export interface GameMetricsDto {
  total: number;
  free: number;
  paid: number;
  completed: number;
  avgPlayers: number;
  endReasons: Record<string, number>;
}

export interface GrantPassRequestDto {
  type: string;
  days: number;
}

export interface HostDto {
  lineId?: string;
  text?: string;
  audioId?: string;
  skipped: boolean;
  aboutYou?: boolean;
  canSkip?: boolean;
}

export interface IntakeDto {
  questions?: string[];
  done: number;
  total: number;
}

export interface JoinRequestDto {
  name: string;
  emoji: string;
}

export interface JoinedDto {
  playerId: string;
  playerToken: string;
}

export interface KindVoteDto {
  voters?: Record<string, string[]>;
  myKind?: RoundKind;
}

export interface LinkRequestDto {
  token: string;
}

export interface LiveStatsDto {
  rooms: number;
  inGame: number;
  players: number;
  viewers: number;
}

export interface LobbyDto {
  joinUrl?: string;
  audienceUrl?: string;
  audienceCount: number;
  minPlayers: number;
  maxPlayers: number;
  botsAllowed?: boolean;
}

export interface MoneyMetricsDto {
  revenue: CurrencyTotalDto[];
  purchases: number;
  byProduct: Record<string, number>;
  refunds: number;
}

export interface NotAppliedEventDto {
  eventId: string;
  eventType: string;
  receivedAt: string;
  action: string;
  status: string;
  txnId: string;
  reason: string;
  detail: string;
  purchaseId: string;
  product: string;
  amountMinor: number;
  currency: string;
  purchaseStatus: string;
  userId: string;
  userEmail: string;
  passId: string;
  passRevokedAt: string;
  passEndsAt: string;
  passHeld: boolean;
}

export interface OfferDto {
  product: Product;
  priceId: string;
  listPriceUsdCents: number;
  monthlyGameLimit: number;
  validityHours: number;
}

export interface OptionDto {
  id?: string;
  text?: string;
  playerId?: string;
  votes?: number;
  audienceVotes?: number;
  authorId?: string;
  points?: number;
  winner?: boolean;
  correct?: boolean;
}

export interface PageDto<T> {
  items: T[];
  page: number;
  size: number;
  totalItems: number;
  totalPages: number;
}

export interface PassLogEntryDto {
  id: string;
  type: Product;
  source: PassSource;
  status: PassLogStatus;
  userId: string;
  userEmail: string;
  userDeleted: boolean;
  createdAt: string;
  startsAt: string;
  endsAt: string;
  monthlyGameLimit: number;
  gamesPlayed: number;
  txnId: string;
  amountMinor: number;
  currency: string;
  refundedAt: string;
  refundKind: string;
  grantedByEmail: string;
  revokedAt: string;
  revokeReason: string;
  revokedByEmail: string;
}

export type PassLogStatus = "ACTIVE" | "UPCOMING" | "EXPIRED" | "REVOKED" | "REFUNDED";

export interface PassRevokedDto {
  revoked: boolean;
}

export type PassSource = "PURCHASE" | "GRANT";

export interface PassStatusDto {
  id: string;
  type: Product;
  startsAt: string;
  endsAt: string;
  monthlyGameLimit: number;
  gamesLeftThisMonth: number;
  grantedByAdmin: boolean;
}

export interface PassSummaryDto {
  sold: number;
  granted: number;
  refunded: number;
  chargebacks: number;
  refundRate: number;
  activeNow: number;
  revenue: CurrencyRevenueDto[];
  byType: Record<string, PassTypeStatsDto>;
}

export interface PassTypeStatsDto {
  sold: number;
  granted: number;
  refunded: number;
  chargebacks: number;
}

export type PauseReason = "OWNER" | "SCREEN_LOST" | "WAITING_FOR_PLAYERS";

export interface PausedDto {
  reason?: PauseReason;
  welcomeBack: boolean;
  remainingMs?: number;
}

export type Phase = "LOBBY" | "INTAKE" | "ROUND_VOTE" | "ANSWERING" | "VOTING" | "REVEAL" | "FINALE" | "CLOSED";

export interface PlayerDto {
  id?: string;
  name?: string;
  emoji?: string;
  connected: boolean;
  score: number;
  captain: boolean;
  status?: string;
  rank?: number;
  bot?: boolean;
}

export type Product = "PARTY_PASS" | "HOST_PASS";

export interface ProfileDto {
  id: string;
  email: string;
  displayName: string;
  role: string;
  googleLinked: boolean;
}

export interface RateLimitWindowDto {
  limit: number;
  remaining: number;
  reset: string;
}

export interface RateLimitsDto {
  capturedAt: string;
  httpStatus: number;
  requests: RateLimitWindowDto;
  tokens: RateLimitWindowDto;
  inputTokens: RateLimitWindowDto;
  outputTokens: RateLimitWindowDto;
  retryAfter: string;
}

export type Role = "OWNER_SCREEN" | "CAPTAIN" | "PLAYER" | "SCREEN" | "AUDIENCE";

export type RoomMode = "STANDARD" | "STREAMER";

export interface RoomSettingsDto {
  tone?: Tone;
  length?: GameLength;
  mode?: RoomMode;
  hideCode: boolean;
  language?: string;
}

export interface RoomStateDto {
  version: number;
  serverTime: number;
  code?: string;
  phase?: Phase;
  deadline?: number;
  paused?: PausedDto;
  waiting?: WaitingDto;
  thinking: boolean;
  locked: boolean;
  settings?: RoomSettingsDto;
  lobby?: LobbyDto;
  players?: PlayerDto[];
  you?: YouDto;
  host?: HostDto;
  intake?: IntakeDto;
  kindVote?: KindVoteDto;
  round?: RoundDto;
  finale?: FinaleDto;
  secrets?: number;
  secretsOpen?: boolean;
  starting: boolean;
  paywall?: ErrorCode;
  sessionId?: string;
  audience?: AudienceDto;
}

export interface RoomStatusDto {
  code: string;
  phase: Phase;
  mode: RoomMode;
  players: number;
  maxPlayers: number;
  locked: boolean;
  full: boolean;
  joinable: boolean;
  audienceOpen: boolean;
  hideCode: boolean;
  audienceKey: string;
  language: string;
}

export interface RoundDto {
  n: number;
  of: number;
  kind?: RoundKind;
  duelIndex?: number;
  duelCount?: number;
  prompt?: string;
  question?: string;
  statement?: string;
  subjectId?: string;
  options?: OptionDto[];
  voters?: string[];
  eligible?: number;
  landslide?: boolean;
  lastOfRound?: boolean;
  points?: Record<string, number>;
  audienceTotal?: number;
  progress?: AnswerProgressDto[];
}

export type RoundKind = "ANSWER_DUEL" | "WHO_OF_US" | "TRUTH_OR_AI";

export interface ScreenTokenDto {
  screenToken: string;
}

export interface SettingValueRequestDto {
  value: unknown;
}

export interface SignedInDto {
  ok: boolean;
}

export interface StatusDto {
  drainMode: boolean;
  freeGamesEnabled: boolean;
  version: string;
}

export type Tone = "FAMILY" | "CHEEKY" | "SPICY";

export interface WaitingDto {
  deadline: number;
  missing?: string[];
}

export interface WebhookOutcomeDto {
  processed: boolean;
  result: string;
}

export interface YouDto {
  role?: Role;
  playerId?: string;
  name?: string;
  emoji?: string;
  score?: number;
  rank?: number;
  canVote?: boolean;
  voted?: boolean;
  myVote?: string;
  secretsLeft?: number;
  intakeNeeded?: boolean;
  assignments?: AssignmentDto[];
  subject?: boolean;
  inDuel?: boolean;
  roundPoints?: number;
  title?: string;
}
