package com.insidejoke.common;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.insidejoke.support.ClassScanUtils;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.RecordComponent;
import java.lang.reflect.Type;
import java.lang.reflect.TypeVariable;
import java.lang.reflect.WildcardType;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.temporal.Temporal;
import java.util.ArrayDeque;
import java.util.Arrays;
import java.util.Collection;
import java.util.Deque;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.UUID;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;

/**
 * Generates the TypeScript contract ({@code frontend/src/lib/api/contract.gen.ts}) from the API records: every record in
 * a {@code ..dto} package, the records and enums they use. The committed file must match
 * what the backend would generate; after changing the contract, regenerate it with
 * {@code ./mvnw -pl backend test -Dtest=ContractTypesTest -Dcontract.update=true}.
 */
class ContractTypesTest {

    private static final Path OUTPUT = Path.of("..", "frontend", "src", "lib", "api", "contract.gen.ts");

    @Test
    void theFrontendContractMatchesTheBackend() throws Exception {
        String generated = generate();
        if (Boolean.getBoolean("contract.update")) {
            Files.createDirectories(OUTPUT.getParent());
            Files.writeString(OUTPUT, generated);
        }
        String committed = Files.exists(OUTPUT) ? Files.readString(OUTPUT) : "";
        assertThat(committed)
                .as("frontend/src/lib/api/contract.gen.ts is out of date; regenerate it with "
                        + "./mvnw -pl backend test -Dtest=ContractTypesTest -Dcontract.update=true")
                .isEqualTo(generated);
    }

    static String generate() throws ClassNotFoundException {
        var contracts = ClassScanUtils.scanner(c -> "java.lang.Record".equals(c.getSuperClassName())
                && c.getClassName().matches("com\\.insidejoke\\..*\\.dto\\.[A-Za-z]+"));
        Deque<Class<?>> queue = new ArrayDeque<>();
        for (var d : contracts.findCandidateComponents("com.insidejoke")) {
            queue.add(Class.forName(d.getBeanClassName()));
        }
        Map<String, String> out = new TreeMap<>();
        while (!queue.isEmpty()) {
            Class<?> c = queue.poll();
            if (out.containsKey(c.getSimpleName())) {
                continue;
            }
            if (c.isEnum()) {
                out.put(
                        c.getSimpleName(),
                        "export type " + c.getSimpleName() + " = "
                                + Arrays.stream(c.getEnumConstants())
                                        .map(e -> "\"" + ((Enum<?>) e).name() + "\"")
                                        .collect(Collectors.joining(" | "))
                                + ";\n");
                continue;
            }
            boolean omitNulls = c.isAnnotationPresent(JsonInclude.class)
                    && c.getAnnotation(JsonInclude.class).value() == JsonInclude.Include.NON_NULL;
            StringBuilder ts = new StringBuilder("export interface " + c.getSimpleName());
            TypeVariable<?>[] vars = c.getTypeParameters();
            if (vars.length > 0) {
                ts.append(Arrays.stream(vars).map(TypeVariable::getName).collect(Collectors.joining(", ", "<", ">")));
            }
            ts.append(" {\n");
            for (RecordComponent rc : c.getRecordComponents()) {
                boolean optional = omitNulls && !rc.getType().isPrimitive();
                ts.append("  ")
                        .append(rc.getName())
                        .append(optional ? "?: " : ": ")
                        .append(ts(rc.getGenericType(), queue))
                        .append(";\n");
            }
            out.put(c.getSimpleName(), ts.append("}\n").toString());
        }
        return "// Generated by ContractTypesTest from the backend API records. Do not edit by hand.\n"
                + "// Fields of records that omit nulls (the WebSocket protocol) are optional here.\n\n"
                + String.join("\n", out.values());
    }

    private static String ts(Type type, Deque<Class<?>> queue) {
        if (type instanceof TypeVariable<?> v) {
            return v.getName();
        }
        if (type instanceof WildcardType w) {
            return ts(w.getUpperBounds()[0], queue);
        }
        if (type instanceof ParameterizedType p) {
            Class<?> raw = (Class<?>) p.getRawType();
            Type[] args = p.getActualTypeArguments();
            if (Collection.class.isAssignableFrom(raw)) {
                String inner = ts(args[0], queue);
                return inner.contains(" ") ? "(" + inner + ")[]" : inner + "[]";
            }
            if (Map.class.isAssignableFrom(raw)) {
                return "Record<string, " + ts(args[1], queue) + ">";
            }
            String params = Arrays.stream(args).map(a -> ts(a, queue)).collect(Collectors.joining(", "));
            queue.add(raw);
            return raw.getSimpleName() + "<" + params + ">";
        }
        Class<?> c = (Class<?>) type;
        if (c == String.class
                || c == char.class
                || c == Character.class
                || c == UUID.class
                || Temporal.class.isAssignableFrom(c)) {
            return "string";
        }
        if (c == boolean.class || c == Boolean.class) {
            return "boolean";
        }
        if (c.isPrimitive() || Number.class.isAssignableFrom(c)) {
            return "number";
        }
        if (c.isEnum() || c.isRecord()) {
            queue.add(c);
            return c.getSimpleName();
        }
        if (Set.of("JsonNode", "Object").contains(c.getSimpleName())) {
            return "unknown";
        }
        return "unknown /* " + c.getSimpleName() + " */";
    }

    @Test
    void everyContractTypeIsNamedByTheConvention() throws Exception {
        List<String> names = Arrays.stream(generate().split("\n"))
                .filter(l -> l.startsWith("export interface "))
                .map(l -> l.substring("export interface ".length()).split("[ <]")[0])
                .toList();
        assertThat(names).as("contract records end with Dto").allMatch(n -> n.endsWith("Dto"));
    }
}
